# -*- coding: utf-8 -*-
"""Copy of evidently.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jXNGBVSZoksDFpEk0wpAAw63PLl8KJeI
"""

# !pip install evidently

import pandas as pd
import numpy as np

# from sklearn.datasets import fetch_california_housing

from evidently import ColumnMapping

from evidently.report import Report
from evidently.metrics.base_metric import generate_column_metrics
from evidently.metric_preset import DataDriftPreset, TargetDriftPreset
from evidently.metrics import *
from evidently import ColumnMapping

from evidently.test_suite import TestSuite
from evidently.tests.base_test import generate_column_tests
from evidently.test_preset import DataStabilityTestPreset, NoTargetPerformanceTestPreset
from evidently.tests import *

"""# New section"""

df = pd.read_csv(
    r"Indian Liver Patient Dataset (ILPD).csv",
    encoding='unicode_escape')
dummy = pd.read_csv(r"dummyyy.csv")

df.rename(columns={"65": "age", "Female": "gender", "0.7": "TB", "0.1": "DB", "187": "Alpkhos",
                   "16": "SGPT", "18": "SGOT", "6.8": "TP", "3.3": "ALB", "0.9": "AG", "1": "target"}, inplace=True)
df

column_mapping = ColumnMapping()
column_mapping.target = "target"
column_mapping.numerical_features = [
    'age', 'TB', 'DB', 'Alpkhos', 'SGPT', 'SGOT', 'TP', 'ALB', 'AG']
column_mapping.categorical_features = ['gender']
column_mapping.task = 'classification'
column_mapping.prediction = "prediction"
column_mapping.target_names = ["1", "2"]


def get_report(current):
    report = Report(metrics=[
        DataDriftPreset(),
        TargetDriftPreset(),
        DatasetCorrelationsMetric()
    ])

    report.run(reference_data=df, current_data=current,
               column_mapping=column_mapping)

    print(report.json())
    report.save_html(name)


name = "file.html"
get_report(dummy)
