apiVersion: v1
kind: Pod
metadata:
  name: final-report
spec:
  containers:
    - name: web
      image: nginx:latest
      volumeMounts: 
        name: pvc-volume-mlops
        mountPath: /var/temp/csvdata
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
      volumes:
    - name: pvc-volume-mlops
      persistentVolumeClaim:
        claimName: pvc-volume-mlops